# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/hodovani/pre-commit-swift
    rev: master
    hooks:
      - id: swift-format
