name: Build, Package, and Upload

on:
  release:
    types: [created]

jobs:
  PackageOnMacOS-x86_64:
    runs-on: macos-latest
    outputs:
      SHA-AMD64: ${{ steps.build-and-package.outputs.SHA-AMD64 }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and Package
        id: build-and-package
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          swift build -c release
          mkdir LFSPointers-$TAG-macOS-amd64
          cp .build/release/LFSPointers LFSPointers-$TAG-macOS-amd64
          tar -czf LFSPointers-$TAG-macOS-amd64.tar.gz LFSPointers-$TAG-macOS-amd64
          export SHA256="$(cat LFSPointers-$TAG-macOS-amd64.tar.gz | shasum -a 256 | cut -d " " -f 1)"
          echo "::set-output name=SHA-AMD64::$SHA256"
      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: LFSPointers-${{ github.event.release.tag_name }}-macOS-amd64.tar.gz
          asset_name: LFSPointers-${{ github.event.release.tag_name }}-macOS-amd64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
          
  PackageOnMacOSForARM64:
    runs-on: macos-latest
    outputs:
      SHA-ARM64: ${{ steps.build-and-package.outputs.SHA-ARM64 }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and Package
        id: build-and-package
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          swift build -c release --arch arm64
          mkdir LFSPointers-$TAG-macOS-arm64
          cp .build/release/LFSPointers LFSPointers-$TAG-macOS-arm64
          tar -czf LFSPointers-$TAG-macOS-arm64.tar.gz LFSPointers-$TAG-macOS-arm64
          export SHA256="$(cat LFSPointers-$TAG-macOS-arm64.tar.gz | shasum -a 256 | cut -d " " -f 1)"
          echo "::set-output name=SHA-ARM64::$SHA256"
      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: LFSPointers-${{ github.event.release.tag_name }}-macOS-arm64.tar.gz
          asset_name: LFSPointers-${{ github.event.release.tag_name }}-macOS-arm64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
  PackageOnUbuntu-ARM:
    runs-on: ubuntu-latest
    outputs:
      LINUX_AARCH64_SHA: ${{ steps.setEnv.outputs.LINUX_AARCH64_SHA }}
      LINUX_AARCH64_SHA-DEB: ${{ steps.hashDEB.outputs.LINUX_AARCH64_SHA-DEB }}
      LINUX_AARCH64_SHA-RPM: ${{ steps.hashDEB.outputs.LINUX_AARCH64_SHA-RPM }}
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.7
        id: build-and-package
        env:
          TAG: ${{ github.event.release.tag_name }}
        with:
          architecture: aarch64
          distribution: ubuntu20.04
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          env: |
            TAG: ${{ github.event.release.tag_name }}
          run: |
            export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
            apt update -q && apt upgrade -yq
            apt install -yq curl
            curl -s https://packagecloud.io/install/repositories/swift-arm/release/script.deb.sh | bash
            apt install -yq swiftlang
            swift build -c release --enable-test-discovery --static-swift-stdlib -Xswiftc -static-executable
            cp .build/release/LFSPointers .
            ./LFSPointers --generate-completion-script zsh > _LFSPointers
            ./LFSPointers --generate-completion-script bash > LFSPointers.bash
            mkdir LFSPointers-$TAG-linux-arm64
            cp .build/release/LFSPointers LFSPointers-$TAG-linux-arm64
            tar -czf LFSPointers-${{ github.event.release.tag_name }}-linux-arm64.tar.gz LFSPointers-$TAG-linux-arm64
      - name: SetEnv
        id: setEnv
        run: |
          export SHA256="$(cat LFSPointers-$TAG-linux-arm64.tar.gz | shasum -a 256 | cut -d " " -f 1)"
          echo "::set-output name=LINUX_AARCH64_SHA::$SHA256"
      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: LFSPointers-${{ github.event.release.tag_name }}-linux-arm64.tar.gz
          asset_name: LFSPointers-${{ github.event.release.tag_name }}-linux-arm64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
      - uses: kentik/pkg@v1.0.0-rc6
        with:
          name: LFSPointers
          version: ${{ github.event.release.tag_name }}
          arch: aarch64
          format: deb
          package: package.yaml
      - uses: kentik/pkg@v1.0.0-rc6
        with:
          name: LFSPointers
          version: ${{ github.event.release.tag_name }}
          arch: aarch64
          format: rpm
          package: package.yaml
      - name: Hash Deb and RPM
        id: hashDEB
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          # DEB
          export SHA256="$(cat LFSPointers_$TAG-1_arm64.deb | shasum -a 256 | cut -d " " -f 1)"
          echo "::set-output name=LINUX_AARCH64_SHA-DEB::$SHA256"
          
          # RPM
          export SHA256="$(cat LFSPointers-$TAG-1.aarch64.rpm | shasum -a 256 | cut -d " " -f 1)"
          echo "::set-output name=LINUX_AARCH64_SHA-RPM::$SHA256"
      - name: Upload Deb
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.deb
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
          file_glob: true
      - name: Upload RPM
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.rpm
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
          file_glob: true
  PackageOnUbuntu-x86_64:
    runs-on: ubuntu-latest
    container: swift:latest
    outputs:
      SHA-TAR: ${{ steps.build-and-package.outputs.SHA-TAR }}
      SHA-DEB: ${{ steps.hashDeb.outputs.SHA-DEB }}
      SHA-RPM: ${{ steps.hashDeb.outputs.SHA-RPM }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and Package
        id: build-and-package
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          swift build -c release --enable-test-discovery --static-swift-stdlib -Xswiftc -static-executable
          cp .build/release/LFSPointers .
          ./LFSPointers --generate-completion-script zsh > _LFSPointers
          ./LFSPointers --generate-completion-script bash > LFSPointers.bash
          mkdir LFSPointers-$TAG-linux-amd64
          cp .build/release/LFSPointers LFSPointers-$TAG-linux-amd64
          tar -czf LFSPointers-$TAG-linux-amd64.tar.gz LFSPointers-$TAG-linux-amd64
          export SHA256="$(cat LFSPointers-$TAG-linux-amd64.tar.gz | shasum -a 256 | cut -d " " -f 1)"
          echo "::set-output name=SHA-TAR::$SHA256"
      - uses: kentik/pkg@v1.0.0-rc6
        with:
          name: LFSPointers
          version: ${{ github.event.release.tag_name }}
          arch: x86_64
          format: deb
          package: package.yaml
      - uses: kentik/pkg@v1.0.0-rc6
        with:
          name: LFSPointers
          version: ${{ github.event.release.tag_name }}
          arch: x86_64
          format: rpm
          package: package.yaml
      - name: Hash Deb
        id: hashDeb
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          export SHA256="$(cat LFSPointers_$TAG-1_amd64.deb | shasum -a 256 | cut -d " " -f 1)"
          echo "::set-output name=SHA-DEB::$SHA256"
          export SHA256="$(cat LFSPointers-$TAG-1.x86_64.rpm | shasum -a 256 | cut -d " " -f 1)"
          echo "::set-output name=SHA-RPM::$SHA256"
      - name: Upload Deb
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.deb
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
          file_glob: true
      - name: Upload RPM
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.rpm
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
          file_glob: true
      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: LFSPointers-${{ github.event.release.tag_name }}-linux-amd64.tar.gz
          asset_name: LFSPointers-${{ github.event.release.tag_name }}-linux-amd64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
  UpdateRelease:
    needs: [PackageOnMacOS-x86_64, PackageOnMacOSForARM64, PackageOnUbuntu-x86_64, PackageOnUbuntu-ARM]
    runs-on: ubuntu-latest
    steps:
      - name: Add SHA256
        uses: tubone24/update_release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            # Hashes

            LFSPointers-${{ github.event.release.tag_name }}-macOS-amd64.tar.gz

            ```
            ${{ needs.PackageOnMacOS-x86_64.outputs.SHA-AMD64 }}
            ```
            
            LFSPointers-${{ github.event.release.tag_name }}-macOS-arm64.tar.gz

            ```
            ${{ needs.PackageOnMacOSForARM64.outputs.SHA-ARM64 }}
            ```

            LFSPointers-${{ github.event.release.tag_name }}-linux-amd64.tar.gz

            ```
            ${{ needs.PackageOnUbuntu-x86_64.outputs.SHA-TAR }}
            ```

            LFSPointers_${{ github.event.release.tag_name }}-1_amd64.deb

            ```
            ${{ needs.PackageOnUbuntu-x86_64.outputs.SHA-DEB }}
            ```

            LFSPointers_${{ github.event.release.tag_name }}-1.x86_64.rpm

            ```
            ${{ needs.PackageOnUbuntu-x86_64.outputs.SHA-RPM }}
            ```
            
            LFSPointers-${{ github.event.release.tag_name }}-linux-arm64.tar.gz

            ```
            ${{ needs.PackageOnUbuntu-ARM.outputs.LINUX_AARCH64_SHA }}
            ```
            
            LFSPointers_${{ github.event.release.tag_name }}-1_arm64.deb

            ```
            ${{ needs.PackageOnUbuntu-ARM.outputs.LINUX_AARCH64_SHA-DEB }}
            ```

            LFSPointers-${{ github.event.release.tag_name }}-1.aarch64.rpm

            ```
            ${{ needs.PackageOnUbuntu-ARM.outputs.LINUX_AARCH64_SHA-RPM }}
            ```
            